### ISSUE TITLE
MANY MANY PROBLEMS

### ISSUE THREAD

**Issue by eso71** [ba0f3/CNCTAScriptCollection#38]
After last update many incoming problems :(
No auto repair, no zoom and many other little things :(
Is it possible to fix it as soon as possible?
Thanks a lot for all this work
Regards
Davide

**Comment by kad** [comment]
some updates are at cncscripts.com

**Comment by rgv151** [comment]
updated

**Comment by eso71** [comment]
Thanks a lot for it!
